// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvgrt8WaMeAAsZlCiPyg73v4OSoguQils',
    appId: '1:1006507047302:web:77df00f56370d30d2f5407',
    messagingSenderId: '1006507047302',
    projectId: 'company-test-5fa56',
    authDomain: 'company-test-5fa56.firebaseapp.com',
    storageBucket: 'company-test-5fa56.appspot.com',
    measurementId: 'G-VFWSRP167X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANCFrka_c10MuZ3yqzy0i2e0h3XgMHNbU',
    appId: '1:1006507047302:android:09f6996edac853b52f5407',
    messagingSenderId: '1006507047302',
    projectId: 'company-test-5fa56',
    storageBucket: 'company-test-5fa56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARI5beEM2d4d_1JLCE7RNFB4mvUYfNEps',
    appId: '1:1006507047302:ios:b88d130a854512172f5407',
    messagingSenderId: '1006507047302',
    projectId: 'company-test-5fa56',
    storageBucket: 'company-test-5fa56.appspot.com',
    iosClientId: '1006507047302-cv247q9vi483cm421grfcuq5bn8rgrjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.companyTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARI5beEM2d4d_1JLCE7RNFB4mvUYfNEps',
    appId: '1:1006507047302:ios:b88d130a854512172f5407',
    messagingSenderId: '1006507047302',
    projectId: 'company-test-5fa56',
    storageBucket: 'company-test-5fa56.appspot.com',
    iosClientId: '1006507047302-cv247q9vi483cm421grfcuq5bn8rgrjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.companyTest',
  );
}
